/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Order = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'status' : IDL.Text,
  'upiReference' : IDL.Opt(IDL.Text),
  'address' : IDL.Text,
  'timestamp' : Time,
  'quantity' : IDL.Nat,
  'amount' : IDL.Nat,
});

export const idlService = IDL.Service({
  'createOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [Order],
      [],
    ),
  'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
  'listOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'submitUPIReference' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Order = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'status' : IDL.Text,
    'upiReference' : IDL.Opt(IDL.Text),
    'address' : IDL.Text,
    'timestamp' : Time,
    'quantity' : IDL.Nat,
    'amount' : IDL.Nat,
  });
  
  return IDL.Service({
    'createOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [Order],
        [],
      ),
    'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
    'listOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'submitUPIReference' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };